### ISSUE TITLE
Planing to clean the project..??

### ISSUE THREAD

**Issue by Ramesh-X** [pathnirvana/pitaka.lk#1]
I saw that this project contains lots of unused/unwanted files. This project is more than 500MB in size. 

It can be difficult for someone who is trying to understand the architecture.

Is there any plan to revise the project by removing unwanted things??

**Comment by pathnirvana** [comment]
Except for the dev folder all the other files are used.
What files that you found are unused?

**Comment by Ramesh-X** [comment]
ah.. things that I found are inside `dev`. Thanks!!
