### ISSUE TITLE
(dict) Clicking on a result doesn't refresh the search results

### ISSUE THREAD

**Issue by tharindusathis** [pathnirvana/pitaka.lk#11]
Although the search box is updated with relevant word when a pali word of a result is clicked, it does not perform the search immediately.

**Comment by pathnirvana** [comment]
I am not sure this is really needed. the original thinking was to just copy the clicked word to the search bar so the user can modify the word before searching. I think it is useful to keep the original search results in the view until the user actually commits to a new search

**Comment by tharindusathis** [comment]
If that so better to keep as it is. However, I personally felt that it is more user-friendly to remove that additional key presses.

**Comment by tharindusathis** [comment]
Just to clarify out, what is the use of this additional `.` ( dot character) after the pali word?

![image](https://user-images.githubusercontent.com/34299693/114150079-41240f80-9939-11eb-805d-9903b7d68c4d.png)

**Comment by pathnirvana** [comment]
if I remember correctly it was for doing an exact match on the word. without the dot it will match with any word starting from the search input
